apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: assemblemonitor-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: assemblemonitor-secret # This is the Kubernetes secret that will be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.awsSecretName }} # The name of the secret in AWS Secrets Manager
