services:
  api:
    image: fire2686/assemblemonitor-backend:v1
    container_name: assemblemonitor_api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - assemblemonitor_net

  frontend:
    image: fire2686/assemblemonitor-frontend:v1
    container_name: assemblemonitor_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - assemblemonitor_net

volumes:
  uploads_data:

networks:
  assemblemonitor_net:
    driver: bridge

