apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assemblemonitor-backend-hpa
  namespace: assemblemonitor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assemblemonitor-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assemblemonitor-frontend-hpa
  namespace: assemblemonitor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assemblemonitor-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
