[all:vars]
ansible_user=ubuntu
# Replace this with the path to your .pem file on the Jenkins server
ansible_ssh_private_key_file=/home/ubuntu/AM-Key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
# Set to the private IP of your SonarQube EC2 instance (e.g. 172.31.x.x)
sonarqube-server ansible_host=REPLACE_WITH_SONARQUBE_PRIVATE_IP

[jenkins]
# Since you are running this ON Jenkins, we use localhost!
jenkins-server ansible_host=127.0.0.1 ansible_connection=local

[k3s]
# Set to the private IP of your K3S EC2 instance (e.g. 172.31.x.x)
k3s-server ansible_host=REPLACE_WITH_K3S_PRIVATE_IP
