# This defines a group of servers named 'sonarqube'.
[sonarqube]
# UPDATE THIS IP: Replace <SONARQUBE_IP> with the fresh IP of AM-SonarQube Server before running.
# This line defines a specific server named 'sonarqube-server' within the group.
# ansible_host: The actual IP address of the server.
# ansible_user: The SSH user to connect as.
sonarqube-server ansible_host=<SONARQUBE_IP> ansible_user=ubuntu
