[all:vars]
ansible_user=ubuntu
# Replace this with the path to your .pem file on the Jenkins server
ansible_ssh_private_key_file=/home/ubuntu/AM-Key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
# REPLACE WITH SONARQUBE PRIVATE IP (Starts with 172.31.)
sonarqube-server ansible_host=<SONARQUBE_PRIVATE_IP>

[jenkins]
# Since you are running this ON Jenkins, we use localhost!
jenkins-server ansible_host=127.0.0.1 ansible_connection=local

[k3s]
# REPLACE WITH K3S PRIVATE IP (Starts with 172.31.)
k3s-server ansible_host=<K3S_PRIVATE_IP>
