apiVersion: v1
kind: Service
metadata:
  name: assemblemonitor-backend-nodeport
  namespace: assemblemonitor
spec:
  type: NodePort
  selector:
    app: assemblemonitor-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
