apiVersion: v1
kind: ConfigMap
metadata:
  name: assemblemonitor-config
  namespace: assemblemonitor
data:
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "assemble-monitor-s3-bucket"
  PYTHONPATH: "/app"